### ISSUE TITLE
Corrigir a clonagem de elementos

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/places#2]
https://github.com/ciebit/places/blob/de1099acf83a84aada99d6ec6d98ce0d19bfb8a9/app/Collections/Cities.php#L25

Utilize a palavra reservada `clone`, assim:

```
return clone $this->Cities;
```

**Comment by maikenegreiros** [comment]
Issue resolvida em 17ec42fe4fac1000f5a3cf5c53f6536b73bababf
