### ISSUE TITLE
Organizar bloco de IFs

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/places#3]
https://github.com/ciebit/places/blob/de1099acf83a84aada99d6ec6d98ce0d19bfb8a9/app/Places.php#L59-L72

A organização desse bloco de código não segue a [PSR-2](https://www.php-fig.org/psr/psr-2/#51-if-elseif-else) 

Haverá erros de sintaxe devido essa referência as constantes, faltou o `self::`.
 
Também é possível que ocorra erros, visto que ele tenta acessar propriedades que pode não ser definidas no array. 

Segue uma sugestão:

```
$Repository
->setFilterId($this->filters[self::CITY_ID] ?? 0) 
->setFilterName($this->filters[self::CITY_NAME] ?? ''); 
```

**Comment by maikenegreiros** [comment]
135ea95fe4a38b085b7f05deffd19263df88ce25
