### ISSUE TITLE
Corrigir chamada da função

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/places#5]
https://github.com/ciebit/places/blob/de1099acf83a84aada99d6ec6d98ce0d19bfb8a9/app/Collections/Cities.php#L20

Faltou os parênteses da chamada de função.

**Comment by maikenegreiros** [comment]
Corrigido no commit https://github.com/ciebit/places/commit/6e3b73dc7bd95e7166f63299847002ed2b259217

**Comment by maikenegreiros** [comment]
Correção no commit https://github.com/ciebit/places/commit/6e3b73dc7bd95e7166f63299847002ed2b259217
